title: SeokJin Blog # 사이트 제목
description: Seokjin Blog! # 사이트 설명
theme: just-the-docs

baseurl: "/"
url: "https://seokjinlee1994.github.io"

# Aux links for the upper right navigation
aux_links: 
	"GitHub":
		- "//github.com/seokjin1994"
