title: SeokJin Blog # 사이트 제목
description: Seokjin Blog! # 사이트 설명
theme: just-the-docs

baseurl: "/"
url: "https://seokjinlee1994.github.io"

# Aux links for the upper right navigation
aux_links: 
  GitHub: https://github.com/seokjinlee1994

# Color scheme currently only supports "drak", "light"/nil (default), or a custom scheme that you define
color_scheme: dark

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Enable or disable the site search
# Support true(default) or false
# search_enabled: true
# search:
#   # Split pages into section that can be search individually
#   # Supports 1 - 6, default: 2
#   heading_level: 3
#   # Maximum amount of previews per search result
#   # Default: 3
#   previews: 2
#   # Maximum amount of words to display before a matched word in the preview
#   # Default: 5
#   preview_words_before: 3
#   # Maximum amount of words to display after a matched word in the preview
#   # Default: 10
#   preview_words_after: 3
#   # Set the search token separator
#   # Default: /[\s\-/]+/
#   # Example: enable support for hyphenated search words
#   tokenizer_separator: /[\s/]+/
#   # Display the relative url in search results
#   # Supports true (default) or false
#   rel_url: true
#   # Enable or disable the search button that appears in the bottom right corner of every page
#   # Supports true or false (default)
#   button: false
